#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC1A60EACE707FDA5 (wl@gnu.org)
#
Name     : groff
Version  : 1.22.3
Release  : 21
URL      : https://ftp.gnu.org/gnu/groff/groff-1.22.3.tar.gz
Source0  : https://ftp.gnu.org/gnu/groff/groff-1.22.3.tar.gz
Source99 : https://ftp.gnu.org/gnu/groff/groff-1.22.3.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 GPL-3.0+ MIT
Requires: groff-bin
Requires: groff-data
Requires: groff-man
BuildRequires : bison
BuildRequires : texinfo
Patch1: usr-bin-sed.patch
Patch2: timestamp.patch

%description
This is the GNU `groff' document formatting system.  The version
number is given in the file VERSION.

%package bin
Summary: bin components for the groff package.
Group: Binaries
Requires: groff-data
Requires: groff-man

%description bin
bin components for the groff package.


%package data
Summary: data components for the groff package.
Group: Data

%description data
data components for the groff package.


%package doc
Summary: doc components for the groff package.
Group: Documentation
Requires: groff-man

%description doc
doc components for the groff package.


%package man
Summary: man components for the groff package.
Group: Default

%description man
man components for the groff package.


%prep
%setup -q -n groff-1.22.3
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526227001
%configure --disable-static
make

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 check

%install
export SOURCE_DATE_EPOCH=1526227001
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/groff/glilypond/args.pl
/usr/lib64/groff/glilypond/oop_fh.pl
/usr/lib64/groff/glilypond/subs.pl
/usr/lib64/groff/gpinyin/subs.pl
/usr/lib64/groff/groff_opts_no_arg.txt
/usr/lib64/groff/groff_opts_with_arg.txt
/usr/lib64/groff/groffer/main_subs.pl
/usr/lib64/groff/groffer/man.pl
/usr/lib64/groff/groffer/split_env.sh
/usr/lib64/groff/groffer/subs.pl
/usr/lib64/groff/groffer/version.sh
/usr/lib64/groff/grog/subs.pl

%files bin
%defattr(-,root,root,-)
/usr/bin/addftinfo
/usr/bin/afmtodit
/usr/bin/chem
/usr/bin/eqn
/usr/bin/eqn2graph
/usr/bin/gdiffmk
/usr/bin/glilypond
/usr/bin/gperl
/usr/bin/gpinyin
/usr/bin/grap2graph
/usr/bin/grn
/usr/bin/grodvi
/usr/bin/groff
/usr/bin/groffer
/usr/bin/grog
/usr/bin/grolbp
/usr/bin/grolj4
/usr/bin/gropdf
/usr/bin/grops
/usr/bin/grotty
/usr/bin/hpftodit
/usr/bin/indxbib
/usr/bin/lkbib
/usr/bin/lookbib
/usr/bin/mmroff
/usr/bin/neqn
/usr/bin/nroff
/usr/bin/pdfmom
/usr/bin/pdfroff
/usr/bin/pfbtops
/usr/bin/pic
/usr/bin/pic2graph
/usr/bin/post-grohtml
/usr/bin/pre-grohtml
/usr/bin/preconv
/usr/bin/refer
/usr/bin/roff2dvi
/usr/bin/roff2html
/usr/bin/roff2pdf
/usr/bin/roff2ps
/usr/bin/roff2text
/usr/bin/roff2x
/usr/bin/soelim
/usr/bin/tbl
/usr/bin/tfmtodit
/usr/bin/troff

%files data
%defattr(-,root,root,-)
/usr/share/groff/1.22.3/eign
/usr/share/groff/1.22.3/font/devascii/B
/usr/share/groff/1.22.3/font/devascii/BI
/usr/share/groff/1.22.3/font/devascii/DESC
/usr/share/groff/1.22.3/font/devascii/I
/usr/share/groff/1.22.3/font/devascii/R
/usr/share/groff/1.22.3/font/devdvi/CW
/usr/share/groff/1.22.3/font/devdvi/CWEC
/usr/share/groff/1.22.3/font/devdvi/CWI
/usr/share/groff/1.22.3/font/devdvi/CWIEC
/usr/share/groff/1.22.3/font/devdvi/CWITC
/usr/share/groff/1.22.3/font/devdvi/CWTC
/usr/share/groff/1.22.3/font/devdvi/DESC
/usr/share/groff/1.22.3/font/devdvi/EX
/usr/share/groff/1.22.3/font/devdvi/HB
/usr/share/groff/1.22.3/font/devdvi/HBEC
/usr/share/groff/1.22.3/font/devdvi/HBI
/usr/share/groff/1.22.3/font/devdvi/HBIEC
/usr/share/groff/1.22.3/font/devdvi/HBITC
/usr/share/groff/1.22.3/font/devdvi/HBTC
/usr/share/groff/1.22.3/font/devdvi/HI
/usr/share/groff/1.22.3/font/devdvi/HIEC
/usr/share/groff/1.22.3/font/devdvi/HITC
/usr/share/groff/1.22.3/font/devdvi/HR
/usr/share/groff/1.22.3/font/devdvi/HREC
/usr/share/groff/1.22.3/font/devdvi/HRTC
/usr/share/groff/1.22.3/font/devdvi/MI
/usr/share/groff/1.22.3/font/devdvi/S
/usr/share/groff/1.22.3/font/devdvi/SA
/usr/share/groff/1.22.3/font/devdvi/SB
/usr/share/groff/1.22.3/font/devdvi/SC
/usr/share/groff/1.22.3/font/devdvi/TB
/usr/share/groff/1.22.3/font/devdvi/TBEC
/usr/share/groff/1.22.3/font/devdvi/TBI
/usr/share/groff/1.22.3/font/devdvi/TBIEC
/usr/share/groff/1.22.3/font/devdvi/TBITC
/usr/share/groff/1.22.3/font/devdvi/TBTC
/usr/share/groff/1.22.3/font/devdvi/TI
/usr/share/groff/1.22.3/font/devdvi/TIEC
/usr/share/groff/1.22.3/font/devdvi/TITC
/usr/share/groff/1.22.3/font/devdvi/TR
/usr/share/groff/1.22.3/font/devdvi/TREC
/usr/share/groff/1.22.3/font/devdvi/TRTC
/usr/share/groff/1.22.3/font/devdvi/generate/CompileFonts
/usr/share/groff/1.22.3/font/devdvi/generate/Makefile
/usr/share/groff/1.22.3/font/devdvi/generate/ec.map
/usr/share/groff/1.22.3/font/devdvi/generate/msam.map
/usr/share/groff/1.22.3/font/devdvi/generate/msbm.map
/usr/share/groff/1.22.3/font/devdvi/generate/tc.map
/usr/share/groff/1.22.3/font/devdvi/generate/texb.map
/usr/share/groff/1.22.3/font/devdvi/generate/texex.map
/usr/share/groff/1.22.3/font/devdvi/generate/texi.map
/usr/share/groff/1.22.3/font/devdvi/generate/texmi.map
/usr/share/groff/1.22.3/font/devdvi/generate/texr.map
/usr/share/groff/1.22.3/font/devdvi/generate/texsy.map
/usr/share/groff/1.22.3/font/devdvi/generate/textex.map
/usr/share/groff/1.22.3/font/devdvi/generate/textt.map
/usr/share/groff/1.22.3/font/devhtml/B
/usr/share/groff/1.22.3/font/devhtml/BI
/usr/share/groff/1.22.3/font/devhtml/CB
/usr/share/groff/1.22.3/font/devhtml/CBI
/usr/share/groff/1.22.3/font/devhtml/CI
/usr/share/groff/1.22.3/font/devhtml/CR
/usr/share/groff/1.22.3/font/devhtml/DESC
/usr/share/groff/1.22.3/font/devhtml/I
/usr/share/groff/1.22.3/font/devhtml/R
/usr/share/groff/1.22.3/font/devhtml/S
/usr/share/groff/1.22.3/font/devlatin1/B
/usr/share/groff/1.22.3/font/devlatin1/BI
/usr/share/groff/1.22.3/font/devlatin1/DESC
/usr/share/groff/1.22.3/font/devlatin1/I
/usr/share/groff/1.22.3/font/devlatin1/R
/usr/share/groff/1.22.3/font/devlbp/CB
/usr/share/groff/1.22.3/font/devlbp/CI
/usr/share/groff/1.22.3/font/devlbp/CR
/usr/share/groff/1.22.3/font/devlbp/DESC
/usr/share/groff/1.22.3/font/devlbp/EB
/usr/share/groff/1.22.3/font/devlbp/EI
/usr/share/groff/1.22.3/font/devlbp/ER
/usr/share/groff/1.22.3/font/devlbp/HB
/usr/share/groff/1.22.3/font/devlbp/HBI
/usr/share/groff/1.22.3/font/devlbp/HI
/usr/share/groff/1.22.3/font/devlbp/HNB
/usr/share/groff/1.22.3/font/devlbp/HNBI
/usr/share/groff/1.22.3/font/devlbp/HNI
/usr/share/groff/1.22.3/font/devlbp/HNR
/usr/share/groff/1.22.3/font/devlbp/HR
/usr/share/groff/1.22.3/font/devlbp/TB
/usr/share/groff/1.22.3/font/devlbp/TBI
/usr/share/groff/1.22.3/font/devlbp/TI
/usr/share/groff/1.22.3/font/devlbp/TR
/usr/share/groff/1.22.3/font/devlj4/AB
/usr/share/groff/1.22.3/font/devlj4/ABI
/usr/share/groff/1.22.3/font/devlj4/AI
/usr/share/groff/1.22.3/font/devlj4/ALBB
/usr/share/groff/1.22.3/font/devlj4/ALBR
/usr/share/groff/1.22.3/font/devlj4/AOB
/usr/share/groff/1.22.3/font/devlj4/AOI
/usr/share/groff/1.22.3/font/devlj4/AOR
/usr/share/groff/1.22.3/font/devlj4/AR
/usr/share/groff/1.22.3/font/devlj4/CB
/usr/share/groff/1.22.3/font/devlj4/CBI
/usr/share/groff/1.22.3/font/devlj4/CI
/usr/share/groff/1.22.3/font/devlj4/CLARENDON
/usr/share/groff/1.22.3/font/devlj4/CORONET
/usr/share/groff/1.22.3/font/devlj4/CR
/usr/share/groff/1.22.3/font/devlj4/DESC
/usr/share/groff/1.22.3/font/devlj4/GB
/usr/share/groff/1.22.3/font/devlj4/GBI
/usr/share/groff/1.22.3/font/devlj4/GI
/usr/share/groff/1.22.3/font/devlj4/GR
/usr/share/groff/1.22.3/font/devlj4/LGB
/usr/share/groff/1.22.3/font/devlj4/LGI
/usr/share/groff/1.22.3/font/devlj4/LGR
/usr/share/groff/1.22.3/font/devlj4/MARIGOLD
/usr/share/groff/1.22.3/font/devlj4/OB
/usr/share/groff/1.22.3/font/devlj4/OBI
/usr/share/groff/1.22.3/font/devlj4/OI
/usr/share/groff/1.22.3/font/devlj4/OR
/usr/share/groff/1.22.3/font/devlj4/S
/usr/share/groff/1.22.3/font/devlj4/SYMBOL
/usr/share/groff/1.22.3/font/devlj4/TB
/usr/share/groff/1.22.3/font/devlj4/TBI
/usr/share/groff/1.22.3/font/devlj4/TI
/usr/share/groff/1.22.3/font/devlj4/TNRB
/usr/share/groff/1.22.3/font/devlj4/TNRBI
/usr/share/groff/1.22.3/font/devlj4/TNRI
/usr/share/groff/1.22.3/font/devlj4/TNRR
/usr/share/groff/1.22.3/font/devlj4/TR
/usr/share/groff/1.22.3/font/devlj4/UB
/usr/share/groff/1.22.3/font/devlj4/UBI
/usr/share/groff/1.22.3/font/devlj4/UCB
/usr/share/groff/1.22.3/font/devlj4/UCBI
/usr/share/groff/1.22.3/font/devlj4/UCI
/usr/share/groff/1.22.3/font/devlj4/UCR
/usr/share/groff/1.22.3/font/devlj4/UI
/usr/share/groff/1.22.3/font/devlj4/UR
/usr/share/groff/1.22.3/font/devlj4/WINGDINGS
/usr/share/groff/1.22.3/font/devlj4/generate/Makefile
/usr/share/groff/1.22.3/font/devlj4/generate/special.awk
/usr/share/groff/1.22.3/font/devlj4/generate/special.map
/usr/share/groff/1.22.3/font/devlj4/generate/symbol.map
/usr/share/groff/1.22.3/font/devlj4/generate/text.map
/usr/share/groff/1.22.3/font/devlj4/generate/wingdings.map
/usr/share/groff/1.22.3/font/devpdf/CB
/usr/share/groff/1.22.3/font/devpdf/CBI
/usr/share/groff/1.22.3/font/devpdf/CI
/usr/share/groff/1.22.3/font/devpdf/CR
/usr/share/groff/1.22.3/font/devpdf/DESC
/usr/share/groff/1.22.3/font/devpdf/EURO
/usr/share/groff/1.22.3/font/devpdf/Foundry
/usr/share/groff/1.22.3/font/devpdf/HB
/usr/share/groff/1.22.3/font/devpdf/HBI
/usr/share/groff/1.22.3/font/devpdf/HI
/usr/share/groff/1.22.3/font/devpdf/HR
/usr/share/groff/1.22.3/font/devpdf/S
/usr/share/groff/1.22.3/font/devpdf/TB
/usr/share/groff/1.22.3/font/devpdf/TBI
/usr/share/groff/1.22.3/font/devpdf/TI
/usr/share/groff/1.22.3/font/devpdf/TR
/usr/share/groff/1.22.3/font/devpdf/ZD
/usr/share/groff/1.22.3/font/devpdf/download
/usr/share/groff/1.22.3/font/devpdf/enc/text.enc
/usr/share/groff/1.22.3/font/devpdf/map/dingbats.map
/usr/share/groff/1.22.3/font/devpdf/map/symbolchars
/usr/share/groff/1.22.3/font/devpdf/map/symbolmap
/usr/share/groff/1.22.3/font/devpdf/map/textmap
/usr/share/groff/1.22.3/font/devpdf/util/BuildFoundries
/usr/share/groff/1.22.3/font/devps/AB
/usr/share/groff/1.22.3/font/devps/ABI
/usr/share/groff/1.22.3/font/devps/AI
/usr/share/groff/1.22.3/font/devps/AR
/usr/share/groff/1.22.3/font/devps/BMB
/usr/share/groff/1.22.3/font/devps/BMBI
/usr/share/groff/1.22.3/font/devps/BMI
/usr/share/groff/1.22.3/font/devps/BMR
/usr/share/groff/1.22.3/font/devps/CB
/usr/share/groff/1.22.3/font/devps/CBI
/usr/share/groff/1.22.3/font/devps/CI
/usr/share/groff/1.22.3/font/devps/CR
/usr/share/groff/1.22.3/font/devps/DESC
/usr/share/groff/1.22.3/font/devps/EURO
/usr/share/groff/1.22.3/font/devps/HB
/usr/share/groff/1.22.3/font/devps/HBI
/usr/share/groff/1.22.3/font/devps/HI
/usr/share/groff/1.22.3/font/devps/HNB
/usr/share/groff/1.22.3/font/devps/HNBI
/usr/share/groff/1.22.3/font/devps/HNI
/usr/share/groff/1.22.3/font/devps/HNR
/usr/share/groff/1.22.3/font/devps/HR
/usr/share/groff/1.22.3/font/devps/NB
/usr/share/groff/1.22.3/font/devps/NBI
/usr/share/groff/1.22.3/font/devps/NI
/usr/share/groff/1.22.3/font/devps/NR
/usr/share/groff/1.22.3/font/devps/PB
/usr/share/groff/1.22.3/font/devps/PBI
/usr/share/groff/1.22.3/font/devps/PI
/usr/share/groff/1.22.3/font/devps/PR
/usr/share/groff/1.22.3/font/devps/S
/usr/share/groff/1.22.3/font/devps/SS
/usr/share/groff/1.22.3/font/devps/TB
/usr/share/groff/1.22.3/font/devps/TBI
/usr/share/groff/1.22.3/font/devps/TI
/usr/share/groff/1.22.3/font/devps/TR
/usr/share/groff/1.22.3/font/devps/ZCMI
/usr/share/groff/1.22.3/font/devps/ZD
/usr/share/groff/1.22.3/font/devps/ZDR
/usr/share/groff/1.22.3/font/devps/download
/usr/share/groff/1.22.3/font/devps/freeeuro.afm
/usr/share/groff/1.22.3/font/devps/freeeuro.pfa
/usr/share/groff/1.22.3/font/devps/generate/Makefile
/usr/share/groff/1.22.3/font/devps/generate/afmname
/usr/share/groff/1.22.3/font/devps/generate/dingbats.map
/usr/share/groff/1.22.3/font/devps/generate/dingbats.rmap
/usr/share/groff/1.22.3/font/devps/generate/lgreekmap
/usr/share/groff/1.22.3/font/devps/generate/symbol.sed
/usr/share/groff/1.22.3/font/devps/generate/symbolchars
/usr/share/groff/1.22.3/font/devps/generate/symbolsl.afm
/usr/share/groff/1.22.3/font/devps/generate/textmap
/usr/share/groff/1.22.3/font/devps/prologue
/usr/share/groff/1.22.3/font/devps/symbolsl.pfa
/usr/share/groff/1.22.3/font/devps/text.enc
/usr/share/groff/1.22.3/font/devps/zapfdr.pfa
/usr/share/groff/1.22.3/font/devutf8/B
/usr/share/groff/1.22.3/font/devutf8/BI
/usr/share/groff/1.22.3/font/devutf8/DESC
/usr/share/groff/1.22.3/font/devutf8/I
/usr/share/groff/1.22.3/font/devutf8/R
/usr/share/groff/1.22.3/oldfont/devps/CB
/usr/share/groff/1.22.3/oldfont/devps/CBI
/usr/share/groff/1.22.3/oldfont/devps/CI
/usr/share/groff/1.22.3/oldfont/devps/CR
/usr/share/groff/1.22.3/oldfont/devps/HB
/usr/share/groff/1.22.3/oldfont/devps/HBI
/usr/share/groff/1.22.3/oldfont/devps/HI
/usr/share/groff/1.22.3/oldfont/devps/HNB
/usr/share/groff/1.22.3/oldfont/devps/HNBI
/usr/share/groff/1.22.3/oldfont/devps/HNI
/usr/share/groff/1.22.3/oldfont/devps/HNR
/usr/share/groff/1.22.3/oldfont/devps/HR
/usr/share/groff/1.22.3/oldfont/devps/NB
/usr/share/groff/1.22.3/oldfont/devps/NBI
/usr/share/groff/1.22.3/oldfont/devps/NI
/usr/share/groff/1.22.3/oldfont/devps/NR
/usr/share/groff/1.22.3/oldfont/devps/PB
/usr/share/groff/1.22.3/oldfont/devps/PBI
/usr/share/groff/1.22.3/oldfont/devps/PI
/usr/share/groff/1.22.3/oldfont/devps/PR
/usr/share/groff/1.22.3/oldfont/devps/S
/usr/share/groff/1.22.3/oldfont/devps/SS
/usr/share/groff/1.22.3/oldfont/devps/TB
/usr/share/groff/1.22.3/oldfont/devps/TBI
/usr/share/groff/1.22.3/oldfont/devps/TI
/usr/share/groff/1.22.3/oldfont/devps/TR
/usr/share/groff/1.22.3/oldfont/devps/symbol.afm
/usr/share/groff/1.22.3/oldfont/devps/symbolsl.afm
/usr/share/groff/1.22.3/oldfont/devps/zapfdr.afm
/usr/share/groff/1.22.3/oldfont/devps/zapfdr.ps
/usr/share/groff/1.22.3/pic/chem.pic
/usr/share/groff/1.22.3/tmac/62bit.tmac
/usr/share/groff/1.22.3/tmac/X.tmac
/usr/share/groff/1.22.3/tmac/Xps.tmac
/usr/share/groff/1.22.3/tmac/a4.tmac
/usr/share/groff/1.22.3/tmac/an-ext.tmac
/usr/share/groff/1.22.3/tmac/an-old.tmac
/usr/share/groff/1.22.3/tmac/an.tmac
/usr/share/groff/1.22.3/tmac/andoc.tmac
/usr/share/groff/1.22.3/tmac/composite.tmac
/usr/share/groff/1.22.3/tmac/cp1047.tmac
/usr/share/groff/1.22.3/tmac/cs.tmac
/usr/share/groff/1.22.3/tmac/de.tmac
/usr/share/groff/1.22.3/tmac/den.tmac
/usr/share/groff/1.22.3/tmac/devtag.tmac
/usr/share/groff/1.22.3/tmac/doc-old.tmac
/usr/share/groff/1.22.3/tmac/doc.tmac
/usr/share/groff/1.22.3/tmac/dvi.tmac
/usr/share/groff/1.22.3/tmac/e.tmac
/usr/share/groff/1.22.3/tmac/ec.tmac
/usr/share/groff/1.22.3/tmac/eqnrc
/usr/share/groff/1.22.3/tmac/europs.tmac
/usr/share/groff/1.22.3/tmac/fallbacks.tmac
/usr/share/groff/1.22.3/tmac/fr.tmac
/usr/share/groff/1.22.3/tmac/hdmisc.tmac
/usr/share/groff/1.22.3/tmac/hdtbl.tmac
/usr/share/groff/1.22.3/tmac/html-end.tmac
/usr/share/groff/1.22.3/tmac/html.tmac
/usr/share/groff/1.22.3/tmac/hyphen.cs
/usr/share/groff/1.22.3/tmac/hyphen.den
/usr/share/groff/1.22.3/tmac/hyphen.det
/usr/share/groff/1.22.3/tmac/hyphen.fr
/usr/share/groff/1.22.3/tmac/hyphen.sv
/usr/share/groff/1.22.3/tmac/hyphen.us
/usr/share/groff/1.22.3/tmac/hyphenex.cs
/usr/share/groff/1.22.3/tmac/hyphenex.det
/usr/share/groff/1.22.3/tmac/hyphenex.us
/usr/share/groff/1.22.3/tmac/ja.tmac
/usr/share/groff/1.22.3/tmac/latin1.tmac
/usr/share/groff/1.22.3/tmac/latin2.tmac
/usr/share/groff/1.22.3/tmac/latin5.tmac
/usr/share/groff/1.22.3/tmac/latin9.tmac
/usr/share/groff/1.22.3/tmac/lbp.tmac
/usr/share/groff/1.22.3/tmac/lj4.tmac
/usr/share/groff/1.22.3/tmac/m.tmac
/usr/share/groff/1.22.3/tmac/man.tmac
/usr/share/groff/1.22.3/tmac/mandoc.tmac
/usr/share/groff/1.22.3/tmac/mdoc.tmac
/usr/share/groff/1.22.3/tmac/mdoc/doc-common
/usr/share/groff/1.22.3/tmac/mdoc/doc-ditroff
/usr/share/groff/1.22.3/tmac/mdoc/doc-nroff
/usr/share/groff/1.22.3/tmac/mdoc/doc-syms
/usr/share/groff/1.22.3/tmac/me.tmac
/usr/share/groff/1.22.3/tmac/mm.tmac
/usr/share/groff/1.22.3/tmac/mm/0.MT
/usr/share/groff/1.22.3/tmac/mm/4.MT
/usr/share/groff/1.22.3/tmac/mm/5.MT
/usr/share/groff/1.22.3/tmac/mm/locale
/usr/share/groff/1.22.3/tmac/mm/ms.cov
/usr/share/groff/1.22.3/tmac/mm/se_locale
/usr/share/groff/1.22.3/tmac/mm/se_ms.cov
/usr/share/groff/1.22.3/tmac/mmse.tmac
/usr/share/groff/1.22.3/tmac/mom.tmac
/usr/share/groff/1.22.3/tmac/ms.tmac
/usr/share/groff/1.22.3/tmac/mse.tmac
/usr/share/groff/1.22.3/tmac/om.tmac
/usr/share/groff/1.22.3/tmac/papersize.tmac
/usr/share/groff/1.22.3/tmac/pdf.tmac
/usr/share/groff/1.22.3/tmac/pdfmark.tmac
/usr/share/groff/1.22.3/tmac/pic.tmac
/usr/share/groff/1.22.3/tmac/ps.tmac
/usr/share/groff/1.22.3/tmac/psatk.tmac
/usr/share/groff/1.22.3/tmac/psold.tmac
/usr/share/groff/1.22.3/tmac/pspic.tmac
/usr/share/groff/1.22.3/tmac/refer-me.tmac
/usr/share/groff/1.22.3/tmac/refer-mm.tmac
/usr/share/groff/1.22.3/tmac/refer-ms.tmac
/usr/share/groff/1.22.3/tmac/refer.tmac
/usr/share/groff/1.22.3/tmac/s.tmac
/usr/share/groff/1.22.3/tmac/safer.tmac
/usr/share/groff/1.22.3/tmac/spdf.tmac
/usr/share/groff/1.22.3/tmac/sv.tmac
/usr/share/groff/1.22.3/tmac/trace.tmac
/usr/share/groff/1.22.3/tmac/trans.tmac
/usr/share/groff/1.22.3/tmac/troffrc
/usr/share/groff/1.22.3/tmac/troffrc-end
/usr/share/groff/1.22.3/tmac/tty-char.tmac
/usr/share/groff/1.22.3/tmac/tty.tmac
/usr/share/groff/1.22.3/tmac/unicode.tmac
/usr/share/groff/1.22.3/tmac/www.tmac
/usr/share/groff/current
/usr/share/groff/site-tmac/man.local
/usr/share/groff/site-tmac/mdoc.local

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/groff/*
%doc /usr/share/info/*

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/addftinfo.1
/usr/share/man/man1/afmtodit.1
/usr/share/man/man1/chem.1
/usr/share/man/man1/eqn.1
/usr/share/man/man1/eqn2graph.1
/usr/share/man/man1/gdiffmk.1
/usr/share/man/man1/glilypond.1
/usr/share/man/man1/gperl.1
/usr/share/man/man1/gpinyin.1
/usr/share/man/man1/grap2graph.1
/usr/share/man/man1/grn.1
/usr/share/man/man1/grodvi.1
/usr/share/man/man1/groff.1
/usr/share/man/man1/groffer.1
/usr/share/man/man1/grog.1
/usr/share/man/man1/grohtml.1
/usr/share/man/man1/grolbp.1
/usr/share/man/man1/grolj4.1
/usr/share/man/man1/gropdf.1
/usr/share/man/man1/grops.1
/usr/share/man/man1/grotty.1
/usr/share/man/man1/hpftodit.1
/usr/share/man/man1/indxbib.1
/usr/share/man/man1/lkbib.1
/usr/share/man/man1/lookbib.1
/usr/share/man/man1/mmroff.1
/usr/share/man/man1/neqn.1
/usr/share/man/man1/nroff.1
/usr/share/man/man1/pdfmom.1
/usr/share/man/man1/pdfroff.1
/usr/share/man/man1/pfbtops.1
/usr/share/man/man1/pic.1
/usr/share/man/man1/pic2graph.1
/usr/share/man/man1/preconv.1
/usr/share/man/man1/refer.1
/usr/share/man/man1/roff2dvi.1
/usr/share/man/man1/roff2html.1
/usr/share/man/man1/roff2pdf.1
/usr/share/man/man1/roff2ps.1
/usr/share/man/man1/roff2text.1
/usr/share/man/man1/roff2x.1
/usr/share/man/man1/soelim.1
/usr/share/man/man1/tbl.1
/usr/share/man/man1/tfmtodit.1
/usr/share/man/man1/troff.1
/usr/share/man/man5/groff_font.5
/usr/share/man/man5/groff_out.5
/usr/share/man/man5/groff_tmac.5
/usr/share/man/man5/lj4_font.5
/usr/share/man/man7/ditroff.7
/usr/share/man/man7/groff.7
/usr/share/man/man7/groff_char.7
/usr/share/man/man7/groff_diff.7
/usr/share/man/man7/groff_filenames.7
/usr/share/man/man7/groff_hdtbl.7
/usr/share/man/man7/groff_man.7
/usr/share/man/man7/groff_mdoc.7
/usr/share/man/man7/groff_me.7
/usr/share/man/man7/groff_mm.7
/usr/share/man/man7/groff_mmse.7
/usr/share/man/man7/groff_mom.7
/usr/share/man/man7/groff_ms.7
/usr/share/man/man7/groff_trace.7
/usr/share/man/man7/groff_www.7
/usr/share/man/man7/roff.7
